title       = "artic"
baseURL     = "https://artic-cli.tamnd.com/"
description = "A command line for artic."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/artic-cli"
